// web-app/nuxt-online-store/components/Card.vue
<template>
  <li class="page__card card" data-id="example">
    <div class="card__panel">
      <a class="card__rating item__rating" href="#">
        <img src="assets/img/icons/star.svg" alt="star" />
        <span class="card__rating item__rating-ratio" data-ratio="${rating}">${rating}</span>
      </a>
      <a class="card__cart" href="#">
        <img src="assets/img/icons/cart.svg" alt="star" />
      </a>
    </div>
    <div class="card__image-block item__image-block">
      <img src="${this.apiBase}${photo}" alt="${name}">
    </div>
    <div class="card__description">
      <a class="card__caption item__caption" href="#">
        ${title}
      </a>
      <b class="card__price item__price">
        ${price} ₽
      </b>
    </div>
  </li>
</template>

<script>
  export default {
    
  }
</script>

<style lang="sass" scoped>
  .card 
    min-height: 270px
    padding: 18px 18px 16px 16px
    display: flex
    flex-direction: column 
    align-items: center
    position: relative
    background: #fff
    box-shadow: 0px 4px 16px rgba(0, 0, 0, 0.05)
    border-radius: 8px
    &__panel 
      width: 88%
      display: flex 
      justify-content: space-between
      align-items: center 
      position: absolute
    &__cart 
      width: 16px 
      height: 16px 
      opacity: 0.4
      transition: $slow
      &:hover 
        opacity: 1
      & img 
        max-width: 100%
        max-height: 100%
    &__image-block 
      max-width: 144px
      max-height: 180px
      & img 
        max-width: 100%
        max-height: 100%
    &__description 
      margin-top: 16px
      display: flex 
      flex-direction: column 
      align-items: flex-start
    

  .selected .card__cart 
    opacity: 1

  @media (max-width: 1200px) 
    .card
      &__image-block  
        max-height: 160px
        max-width: 120px


  @media (max-width: 992px) 
    .card
      &__image-block  
        max-height: 140px
        max-width: 100px

      &__cart
        width: 20px
        height: 20px

  @media (max-width: 576px) 
    .card 
      min-height: 220px
      &__panel
        position: static 
      &__image-block  
        max-height: 150px
        max-width: 120px


  @media (max-width: 576px) 
    .card 
      &__description
        align-items: center 
</style>

// web-app/apartments/src/components/card/card.jsx
import React from 'react';
import styled from 'styled-components';
import PropTypes from 'prop-types';

import Like from '../like';

import apartment from '../../assets/img/apartment.jpg';

export default function Card(props) {
	const { 
		type,
		imgSrc,
		attributes: {
			title,
			rooms,
			address: {
				city,
				street,
				house,
				room
			},
			area,
			unit
		},
		relationships: {
			attributes: {
				first_name,
				last_name,
				middle_name
			}
		}
	} = props;

	return (
		<Content data-type={type}>
			<ImageBlock>
				<img src={imgSrc} alt="apartment" />
			</ImageBlock>
			<Description>
				<Title>
					{title}
				</Title>
				<DescriptionList>
					<ListItem>
						<ListItemCaption>
							Количество комнат:
						</ListItemCaption>
						<span>
							{rooms}
						</span>
					</ListItem>
					<ListItem>
						<ListItemCaption>
							Адрес:
						</ListItemCaption>
						<span>
							{city},
							{street} {house}
							кв. {room}
						</span>
					</ListItem>
					<ListItem>
						<ListItemCaption>
							Площадь:
						</ListItemCaption>
						<span>
							{area} {unit}
						</span>
					</ListItem>
					<ListItem>
						<ListItemCaption>
							Консультант:
						</ListItemCaption>
						<span>
							{last_name} {first_name} {middle_name}
						</span>
					</ListItem>
				</DescriptionList>
			</Description>
			<Like/>
		</Content>
	)
}

Card.propTypes = {
	type: PropTypes.string,
	imgSrc: PropTypes.string.isRequired,
	title: PropTypes.string,
	rooms: PropTypes.number,
	address: PropTypes.string,
	city: PropTypes.string,
	street: PropTypes.string,
	house: PropTypes.string,
	room: PropTypes.string,
	area: PropTypes.number,
	unit: PropTypes.string,
	first_name: PropTypes.string,
	last_name: PropTypes.string,
	middle_name: PropTypes.string
};

Card.defaultProps = {
	type: 'flat',
	imgSrc: apartment
};

const Content = styled.div`
	margin-top: 40px;
	max-width: 300px;
	height: 500px;
	padding-bottom: 25px;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: space-between;
	border-radius: 2%;
	border: 1px solid #999;
	transition: all 0.3s ease 0s;

	&:hover {
		transform: scale(1.05);
		background-color: #fff;
	}

	&:hover h3 {
		color: rgba(0, 0, 0, 1);
	}

	@media (max-width: 375px) {
		margin-top: 30px;
		max-width: 280px;
	}
`;

const ImageBlock = styled.div`
	width: 100%;
	height: 200px;

	& img {
		width: 100%;
		height: 100%;
	}
`;

const Description = styled.div`
	margin-top: 25px;
	padding: 0 10px;
`;

const Title = styled.h3`
	color: rgba(0, 0, 0, 0.8);
	font-size: 20px;
	font-weight: bold;
	text-align: center;
`;

const DescriptionList = styled.ul`
	list-style-type: none;
`;

const ListItem = styled.li`
	margin-top: 5px;
`;

const ListItemCaption = styled.span`
	font-size: 16px;
	font-weight: bold;
`;
